### PR TITLE
Cleaned up

### PR DESCRIPTION
**Pull request by camdenorrb**
I cleaned up some of your code :3

### CODE REVIEW

**Comment by andy1ne0** [comment]
Cheers, I'll look into improving the ping function later today. I'm considering using Jaunt to improve the readability of the code, which also has an integrated JSON library - will investigate options soon.

**Comment by andy1ne0** [comment]
[WIP on a small rewrite using Jaunt](https://github.com/andy1ne0/LeakBlock/tree/indev-1) - I'll finish it tomorrow, feeling a bit under the weather and got schoolwork to do. It's a lot more simplified, as can be seen in the main class for the Bukkit plugin. Sorry for the late follow-up, had some private projects that needed to be done.

**Comment by andy1ne0** [comment]
Update deployed.

**Comment by camdenorrb** [comment]
:3

**Pull request merged**
