### PR TITLE
Big update

### PR DESCRIPTION
**Pull request by Janmm14**
- Update version to 2.0.0
- Add .gitignore file and ignore common files which should not be in the repo
- Fix missing comments in the config file of bungeecord
- Add lombok (requires IDE supportive plugin)
- Better structure
- Removed duplicated code, use more methods and classes (readability, maintainability)
- Use plain java and gson (json library included in bungee and bukkit) instead of Jaunt (smaller file size, plugin will function always and won't require monthly updates)
- Process always asynchroniously
- Remove need of kick delay and have a longer login phase instead (still asynchroniously, so no lag will occurr)
- Add permission `leakblock.notifyupdate`
- Rework events
- Add own cache system with an extra yml file
- Force reset of config file, introduce configversion variable for that

### CODE REVIEW

**Comment by andy1ne0** [comment]
Holy shit, that's huge xD. I'll merge it and release it as 2.0 on the weekend - a bit busy with school atm. Thanks for this tho. (What's your Spigot username, I'll add you as a contributor if you want)

**Comment by andy1ne0** [comment]
The only thing I might change back is when the post processing event is fired - ideally, it should only be fired if the connection is cancelled (to remove extra boilerplate for other developers, and also to reduce confusion).

**Comment by Janmm14** [comment]
My spigot username is the same as here, Janmm14. You can simply put the event firing into the if, but note that this affects caching of "clean" ips, which will be the most and they get checked then over and over again without sense. You could simply state in the update that the events now contain whether things are blocked or not.

**Comment by andy1ne0** [comment]
Ahh I see, that makes more sense haha. I'll leave that as is then, in that case

**Comment by andy1ne0** [comment]
Ahh I see, that makes more sense haha. I'll leave that as is then, in that case

**Comment by andy1ne0** [comment]
All righty, I'll be merging and publishing this tomorrow morning. The only thing I might add is to save the config file every time a new cache item is added, as opposed to on server shutdown - that way, in the event of a server crash the existing data will be preserved.

**Comment by Janmm14** [comment]
That is a good idea.

**Pull request merged**
